//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDENEYIMLER
    {
        public int ID { get; set; }
        public string FIRMAADI { get; set; }
        public string POZISYON { get; set; }
        public string FIRMASEKTOR { get; set; }
        public Nullable<System.DateTime> GIRISTARIH { get; set; }
        public Nullable<System.DateTime> CIKISTARIH { get; set; }
    }
}
