//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDIL
    {
        public int ID { get; set; }
        public string DIL { get; set; }
        public Nullable<int> BASARI { get; set; }
    }
}
